name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this secret contains the new private key

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "
          cd $NGINX_DIR &&
          sudo cp opravAuto.man opravAuto &&
          sudo systemctl restart nginx &&
          pm2 delete server client || true &&
          cd $APP_DIR &&
          git remote set-url origin https://github.com/TomasHusarik/OpravAuto.git &&
          git pull origin main &&
          cd client &&
          npm install &&
          npm run build &&
          pm2 serve --name client dist 8080 --spa &&
          cd ../server &&
          npm install &&
          pm2 start npm --name server -- start &&
          cd $NGINX_DIR &&
          sudo cp opravAuto.run opravAuto &&
          sudo systemctl restart nginx
          "